http:
  middlewares:
    https:
      redirectScheme:
        scheme: https
    # https://doc.traefik.io/traefik/middlewares/basicauth/ <-- BasicAuth Dokumentation
    # htpasswd -h yourname
    auth:
      basicAuth:
        users:
          # ChangeMe
          - 'yourname:bcrypt-hashed-pw'
certificatesResolvers:
  dns:
    acme:
      # ChangeMe
      email: dmail@example.com
      storage: /LetsEncrypt/acme.json
      dnsChallenge:
        provider: cloudflare